import Head from 'next/head'
import React from 'react'
import { CopyBlock, dracula } from 'react-code-blocks';
import Heading from '../components/heading'
import useLocalStorage from '../hooks/useLocalStorage';
import useUpdateLogger from '../hooks/useUpdateLogger';

const CustomHooks = () => {

    const [ name, setName ] = useLocalStorage('name', "");
    useUpdateLogger(name);

    return (
        <div>

            <Head>
                <title>Custom Hooks | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading heading={'Custom Hooks'}/> 

            <CopyBlock
                text="
                    const [ name, setName ] = useLocalStorage('name', '');
                    useUpdateLogger(name);
                "
                language='javascript'
                wrapLines
                theme={dracula}
                codeBlock={true}
            />

            <br />

            <input 
                type="text" 
                value={name}
                onChange={(e) => setName(e.target.value)}
            />

        </div>
    )
}

export default CustomHooks