import Head from 'next/head'
import React, { useState, useCallback } from 'react'
import { CopyBlock, dracula } from 'react-code-blocks';
import Heading from '../components/heading'
import List from '../components/List';

const UseCallBack = () => {

    const [ number, setNumber ] = useState(1);
    const [ dark, setDark ] = useState(false);

    const getItems = useCallback((incrementor) => {
        return [ number + incrementor, number + 1 + incrementor, number + 2 + incrementor]
    }, [number]);

    const theme = {
        backgroundColor: dark ? '#333': '#FFF',
        color: dark ? '#FFF': '#333',
        padding: '20px',
        marginTop: "30px"
    }

    return (
        <div>
            <Head>
                <title>UseCallback | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading heading={'Use Callback'}/>

            <CopyBlock
                text="
                const getItems = useCallback(() => {
                    return [ number, number + 1, number + 2]
                }, [number]);
                "
                language='javascript'
                wrapLines
                theme={dracula}
                codeBlock={true}
            />

            <div style={theme}>
                <input 
                    type="number" 
                    min={0}
                    value={number}
                    onChange={e => setNumber(parseInt(e.target.value))}
                />

                <button
                    onClick={() => setDark(prevDark => !prevDark)}
                >Toggle Theme</button>

                <List getItems={getItems}/>

            </div>

        </div>
    )
}

export default UseCallBack