import React from 'react'
import Heading from '../components/heading'

const UseRef = () => {
    return (
        <div>
            <Head>
                <title>UseRef | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading heading={'Use Ref'} />
        </div>
    )
}

export default UseRef