import Head from 'next/head'
import React, { useState, useTransition } from 'react'
import { CopyBlock, dracula } from 'react-code-blocks';
import Heading from '../components/heading'

const UseTransactionHook = () => {

    const [isPending, startTransition] = useTransition();

    const [ input, setInput ] = useState("");
    const [ list, setList ] = useState([]);

    const LIST_SIZE = 20000;

    function handleChange(e){

        setInput(e.target.value);
        startTransition(() => {
            const l = [];
            for (let i = 0; i < LIST_SIZE; i++) {
                l.push(e.target.value);
            }
            setList(l);
        })

    }

    return (
        <div>
            <Head>
                <title>UseTransaction | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading heading={'Use Transaction Hook'}/>

            <CopyBlock
                text="
                    const [isPending, startTransition] = useTransition();
                    setInput(e.target.value);
                    startTransition(() => {
                        const l = [];
                        for (let i = 0; i < LIST_SIZE; i++) {
                            l.push(e.target.value);
                        }
                        setList(l);
                    })
                "
                language='javascript'
                wrapLines
                theme={dracula}
                codeBlock={true}
            />

            <br />

            <input type="text" placeholder='Enter something...' value={input} onChange={handleChange} />
            {
                isPending ? "loading" : list.map((item, index) => {
                    return (
                        <div key={index}>{item}</div>
                    )
                })
            }
        </div>
    )
}

export default UseTransactionHook