import Head from 'next/head'
import React, { useState, useMemo, useEffect } from 'react'
import Heading from '../components/heading';

const UseMemo = () => {

    const [ number, setNumber ] = useState(0);
    const [ dark, steDark ] = useState(false);

    const doubleNumber = useMemo(() => {
        return slowFunction(number);
    }, [number]);

    

    const themeStyles = useMemo(() => {
        return {
            backgroundColor: dark ? 'skyblue': 'white',
            color: dark ? 'white' : 'black',
            width: "154px",
            borderRadius: "10px",
            padding: "4px",
            textAlign: 'left'
        }
    }, [dark]);

    useEffect(() => {
        console.log("Theme changed");
    }, [themeStyles]);

    return (
        <>
            <Head>
                <title>UseMemo | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Heading heading={'Use Memo'}/>

            <input 
                type="number" 
                value={number} 
                onChange={(e) => setNumber(parseInt(e.target.value))} 
            />

            <button
                onClick={() => steDark(prevDark => !prevDark)}
            >Change Theme</button>

            <div
                style={themeStyles}
            >
                {doubleNumber}
            </div>
        </>
    )
}

export default UseMemo

function slowFunction (num) {
    for(let i = 0; i <= 100000000; i++){}
    return num * 2;
}