import Head from 'next/head'
import React, { useState } from 'react'
import { CopyBlock, dracula } from 'react-code-blocks';
import FunctionContextComponent from '../components/FunctionContextComponent';
import Heading from '../components/heading'
import { ThemeProvider } from '../components/ThemeContext';

export const ThemeContext = React.createContext();

const UseContext = () => {

    return (
        <div>
            <Head>
                <title>UseContext | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading heading={'Use Context'} />

            <CopyBlock
                text="
                    <ThemeContext.Provider value={darkTheme}>
                    </ThemeContext.Provider>
                "
                language='javascript'
                wrapLines
                theme={dracula}
                codeBlock={true}
            />

            <ThemeProvider>
                <FunctionContextComponent/>
            </ThemeProvider>

        </div>
    )
}

export default UseContext