import Head from 'next/head'
import React from 'react'
import Heading from '../components/heading'

const UseLayoutEffect = () => {
    return (
        <div>
            <Head>
                <title>UseLayoutEffect | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading heading={'Use LayoutEffect'}/>

        </div>
    )
}

export default UseLayoutEffect