import Head from 'next/head';
import React, { useState, useEffect } from 'react'
import Heading from '../components/heading';

const UseEffect = () => {

    const [ resourceType, setResourceType ] = useState('posts');
    // const [ windowWidth, setWindowWidth ] = useState(window.innerWidth);
    const [ items, setItems ] = useState([]);

    useEffect(() => {
        fetch(`https://jsonplaceholder.typicode.com/todos/1/${resourceType}`)
        .then(res => res.json())
        .then(json => setItems(json));
    }, [resourceType]);

    // useEffect(() => {
    //     window.addEventListener('resize', handleResize);
    // }, []);

    // const handleResize = () => {
    //     setWindowWidth(window.innerWidth);
    // }

    return (
        <>
            <Head>
                <title>UseEffect | React Hooks Collections</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Heading heading={'Use Effect'}/>
            <button onClick={() => setResourceType('posts')}>Posts</button>
            <button onClick={() => setResourceType('users')}>Users</button>
            <button onClick={() => setResourceType('comments')}>Comments</button>

            {/* <h1>Window Width : {windowWidth}</h1> */}

            <h1>{resourceType}</h1>

            <div
                style={{ width: "100%", overflowY: 'scroll'}}
            >

                {
                    items.map((item, i) => {
                        return (
                            <pre key={i}>
                                {JSON.stringify(item)}
                            </pre>
                        )
                    })
                }

            </div>

        </>
    )
}

export default UseEffect